spin_manifest_version = 2

[application]
name = "spin-microservice-demo"
version = "0.1.0"
authors = ["Suson Waiba <susonwaiba@gmail.com>"]
description = ""

[[trigger.http]]
route = "/ts-adder/..."
component = "ts-adder"

[component.ts-adder]
source = "ts-adder/target/ts-adder.wasm"
[component.ts-adder.build]
command = "npm run build"
workdir = "ts-adder"

[[trigger.http]]
route = "/ts-calculator/..."
component = "ts-calculator"

[component.ts-calculator]
source = "ts-calculator/target/ts-calculator.wasm"
[component.ts-calculator.build]
command = "npm run build"
workdir = "ts-calculator"

[[trigger.http]]
route = "/static/..."
component = "static"

[component.static]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "static", destination = "/" }]

[[trigger.http]]
route = "/rs-adder/..."
component = "rs-adder"

[component.rs-adder]
source = "rs-adder/target/wasm32-wasi/release/rs_adder.wasm"
allowed_outbound_hosts = []
[component.rs-adder.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "rs-adder"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/rs-calculator/..."
component = "rs-calculator"

[component.rs-calculator]
source = "rs-calculator/target/wasm32-wasi/release/rs_calculator.wasm"
allowed_outbound_hosts = []
[component.rs-calculator.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "rs-calculator"
watch = ["src/**/*.rs", "Cargo.toml"]
